[package]
name = "head-of-site"
version = "0.1.0"
edition = "2024"

[dependencies]
topcoat = { version = "0.6.2", features = ["htmx", "ui"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
url = "2"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "charset", "gzip", "brotli", "deflate"] }
scraper = { version = "0.20", features = ["deterministic"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
strip = true
lto = "thin"
